spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/jm?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  messages:
    basename: messages

mybatis:
  mapper-locations: mapper/*.xml

file:
  dir: C:\study\upload\